package client

import (
	"context"
	"crypto/ed25519"
	"encoding/base64"
	"net/http"
	"time"

	"github.com/mevoc/sund/internal/sigauth"
)

// Device is an enrolled device: the management-plane principal. Its identity
// key signs every call; the server looks the key up by ID.
type Device struct {
	conn      *Conn
	ID        string
	AccountID string // known after Register; empty when resumed via NewDevice
	key       ed25519.PrivateKey
}

// DeviceInfo is one row of the account's device list.
type DeviceInfo struct {
	ID        string
	PublicKey ed25519.PublicKey
	// Role is "admin" or "member". A client MUST surface it: authority over
	// other devices has to be visible to the devices it is held over, which is
	// the consumer's half of "no silent administration" (PRD, decision 12).
	// Sund publishes the field and cannot make a client render it.
	Role string
	// PushEndpoint is populated only for the calling device. A peer's wake-up URL
	// is a capability over it, not a fact about it, so the server withholds it
	// (PRD, decision 20).
	PushEndpoint string
	Capabilities string
	Created      time.Time
	LastSeen     time.Time
	Revoked      bool
}

// Invitation is a freshly minted enrollment token. Token is the secret and is
// only ever present on the mint response; ID is non-secret and is what the
// listing and revocation use.
type Invitation struct {
	ID      string
	Token   string
	Expires time.Time
}

// QueueIDs are the two ends of a newly created queue. The sender id (with the
// consumer's payload-encryption key) is handed to the peer out of band.
type QueueIDs struct {
	RecipientID string
	SenderID    string
}

// Register enrolls a new device against a one-time invitation token. key is the
// device's identity key, generated by the caller and stored by it — it never
// leaves the device. pushEndpoint and capabilities may be empty.
func Register(ctx context.Context, conn *Conn, token string, key ed25519.PrivateKey, pushEndpoint, capabilities string) (*Device, error) {
	in := map[string]string{
		"token":         token,
		"public_key":    b64(key.Public().(ed25519.PublicKey)),
		"push_endpoint": pushEndpoint,
		"capabilities":  capabilities,
	}
	var out struct {
		DeviceID  string `json:"device_id"`
		AccountID string `json:"account_id"`
	}
	if err := conn.do(ctx, nil, http.MethodPost, "/v1/devices/register", nil, in, &out); err != nil {
		return nil, err
	}
	return &Device{conn: conn, ID: out.DeviceID, AccountID: out.AccountID, key: key}, nil
}

// NewDevice resumes an already enrolled device from its stored id and key.
func NewDevice(conn *Conn, deviceID string, key ed25519.PrivateKey) *Device {
	return &Device{conn: conn, ID: deviceID, key: key}
}

// PublicKey returns the device's identity public key.
func (d *Device) PublicKey() ed25519.PublicKey { return d.key.Public().(ed25519.PublicKey) }

func (d *Device) do(ctx context.Context, method, path string, in, out any) error {
	h := http.Header{}
	h.Set(sigauth.HeaderDeviceID, d.ID)
	return d.conn.do(ctx, d.key, method, path, h, in, out)
}

// ListDevices returns every device in the account, revoked ones included.
func (d *Device) ListDevices(ctx context.Context) ([]DeviceInfo, error) {
	var out struct {
		Devices []struct {
			ID           string `json:"id"`
			PublicKey    string `json:"public_key"`
			Role         string `json:"role"`
			PushEndpoint string `json:"push_endpoint"`
			Capabilities string `json:"capabilities"`
			Created      string `json:"created"`
			LastSeen     string `json:"last_seen"`
			Revoked      bool   `json:"revoked"`
		} `json:"devices"`
	}
	if err := d.do(ctx, http.MethodGet, "/v1/devices", nil, &out); err != nil {
		return nil, err
	}
	res := make([]DeviceInfo, len(out.Devices))
	for i, v := range out.Devices {
		pk, _ := base64.StdEncoding.DecodeString(v.PublicKey)
		res[i] = DeviceInfo{
			ID: v.ID, PublicKey: ed25519.PublicKey(pk), Role: v.Role,
			PushEndpoint: v.PushEndpoint,
			Capabilities: v.Capabilities, Created: parseTime(v.Created),
			LastSeen: parseTime(v.LastSeen), Revoked: v.Revoked,
		}
	}
	return res, nil
}

// RevokeDevice revokes a device in the account. In a flat account any device may
// revoke any other; in a managed one that is admin-only, and a member revoking
// anything but itself gets 403. Revoking yourself always works.
func (d *Device) RevokeDevice(ctx context.Context, deviceID string) error {
	return d.do(ctx, http.MethodPost, "/v1/devices/"+deviceID+"/revoke", nil, nil)
}

// CreateInvitation mints a single-use token to enroll another device.
func (d *Device) CreateInvitation(ctx context.Context) (Invitation, error) {
	var out struct {
		Token   string `json:"invitation_token"`
		ID      string `json:"invitation_id"`
		Expires string `json:"expires"`
	}
	if err := d.do(ctx, http.MethodPost, "/v1/invitations", nil, &out); err != nil {
		return Invitation{}, err
	}
	return Invitation{ID: out.ID, Token: out.Token, Expires: parseTime(out.Expires)}, nil
}

// ListInvitations returns the account's outstanding invitations, without tokens.
func (d *Device) ListInvitations(ctx context.Context) ([]Invitation, error) {
	var out struct {
		Invitations []struct {
			ID      string `json:"id"`
			Expires string `json:"expires"`
		} `json:"invitations"`
	}
	if err := d.do(ctx, http.MethodGet, "/v1/invitations", nil, &out); err != nil {
		return nil, err
	}
	res := make([]Invitation, len(out.Invitations))
	for i, v := range out.Invitations {
		res[i] = Invitation{ID: v.ID, Expires: parseTime(v.Expires)}
	}
	return res, nil
}

// RevokeInvitation kills a mis-shared invitation before it is used.
func (d *Device) RevokeInvitation(ctx context.Context, invitationID string) error {
	return d.do(ctx, http.MethodPost, "/v1/invitations/"+invitationID+"/revoke", nil, nil)
}

// SetPushEndpoint registers the device's wake-up endpoint (a UnifiedPush URL);
// an empty string clears it.
func (d *Device) SetPushEndpoint(ctx context.Context, endpoint string) error {
	return d.do(ctx, http.MethodPut, "/v1/me/push", map[string]string{"push_endpoint": endpoint}, nil)
}

// PublishBundle stores the device's opaque key bundle for peers to fetch.
func (d *Device) PublishBundle(ctx context.Context, blob []byte) error {
	return d.do(ctx, http.MethodPut, "/v1/me/bundle", map[string]string{"bundle": b64(blob)}, nil)
}

// GetBundle fetches a peer device's published bundle, verbatim.
func (d *Device) GetBundle(ctx context.Context, deviceID string) ([]byte, error) {
	var out struct {
		Bundle string `json:"bundle"`
	}
	if err := d.do(ctx, http.MethodGet, "/v1/devices/"+deviceID+"/bundle", nil, &out); err != nil {
		return nil, err
	}
	return base64.StdEncoding.DecodeString(out.Bundle)
}

// CreateQueue creates a blind queue owned by this device. recipientKey is the
// public half of a fresh per-queue Ed25519 key the caller generated; the
// matching private key goes into a Recipient.
func (d *Device) CreateQueue(ctx context.Context, recipientKey ed25519.PublicKey) (QueueIDs, error) {
	var out struct {
		RecipientID string `json:"recipient_id"`
		SenderID    string `json:"sender_id"`
	}
	in := map[string]string{"recipient_key": b64(recipientKey)}
	if err := d.do(ctx, http.MethodPost, "/v1/queues", in, &out); err != nil {
		return QueueIDs{}, err
	}
	return QueueIDs{RecipientID: out.RecipientID, SenderID: out.SenderID}, nil
}
