package client

import (
	"context"
	"crypto/ed25519"
	"encoding/base64"
	"fmt"
	"net/http"
	"strconv"
	"time"

	"github.com/mevoc/sund/internal/sigauth"
)

// Device is an enrolled device: the management-plane principal. Its identity
// key signs every call; the server looks the key up by ID.
type Device struct {
	conn      *Conn
	ID        string
	AccountID string // known after Register; empty when resumed via NewDevice
	key       ed25519.PrivateKey
}

// DeviceInfo is one row of the account's device list.
type DeviceInfo struct {
	ID        string
	PublicKey ed25519.PublicKey
	// Role is "admin" or "member". A client MUST surface it: authority over
	// other devices has to be visible to the devices it is held over, which is
	// the consumer's half of "no silent administration" (PRD, decision 12).
	// Sund publishes the field and cannot make a client render it.
	Role string
	// PushEndpoint is populated only for the calling device. A peer's wake-up URL
	// is a capability over it, not a fact about it, so the server withholds it
	// (PRD, decision 20).
	PushEndpoint string
	Capabilities string
	Created      time.Time
	LastSeen     time.Time
	Revoked      bool
}

// Invitation is a freshly minted enrollment token. Token is the secret and is
// only ever present on the mint response; ID is non-secret and is what the
// listing and revocation use.
type Invitation struct {
	ID      string
	Token   string
	Expires time.Time
}

// QueueIDs are the two ends of a newly created queue. The sender id (with the
// consumer's payload-encryption key) is handed to the peer out of band.
type QueueIDs struct {
	RecipientID string
	SenderID    string
}

// Register enrolls a new device against a one-time invitation token. key is the
// device's identity key, generated by the caller and stored by it — it never
// leaves the device. pushEndpoint and capabilities may be empty.
func Register(ctx context.Context, conn *Conn, token string, key ed25519.PrivateKey, pushEndpoint, capabilities string) (*Device, error) {
	in := map[string]string{
		"token":         token,
		"public_key":    b64(key.Public().(ed25519.PublicKey)),
		"push_endpoint": pushEndpoint,
		"capabilities":  capabilities,
	}
	var out struct {
		DeviceID  string `json:"device_id"`
		AccountID string `json:"account_id"`
	}
	if err := conn.do(ctx, nil, http.MethodPost, "/v1/devices/register", nil, in, &out); err != nil {
		return nil, err
	}
	return &Device{conn: conn, ID: out.DeviceID, AccountID: out.AccountID, key: key}, nil
}

// NewDevice resumes an already enrolled device from its stored id and key.
func NewDevice(conn *Conn, deviceID string, key ed25519.PrivateKey) *Device {
	return &Device{conn: conn, ID: deviceID, key: key}
}

// PublicKey returns the device's identity public key.
func (d *Device) PublicKey() ed25519.PublicKey { return d.key.Public().(ed25519.PublicKey) }

func (d *Device) do(ctx context.Context, method, path string, in, out any) error {
	h := http.Header{}
	h.Set(sigauth.HeaderDeviceID, d.ID)
	return d.conn.do(ctx, d.key, method, path, h, in, out)
}

// ListDevices returns every device in the account, revoked ones included.
func (d *Device) ListDevices(ctx context.Context) ([]DeviceInfo, error) {
	var out struct {
		Devices []struct {
			ID           string `json:"id"`
			PublicKey    string `json:"public_key"`
			Role         string `json:"role"`
			PushEndpoint string `json:"push_endpoint"`
			Capabilities string `json:"capabilities"`
			Created      string `json:"created"`
			LastSeen     string `json:"last_seen"`
			Revoked      bool   `json:"revoked"`
		} `json:"devices"`
	}
	if err := d.do(ctx, http.MethodGet, "/v1/devices", nil, &out); err != nil {
		return nil, err
	}
	res := make([]DeviceInfo, len(out.Devices))
	for i, v := range out.Devices {
		pk, _ := base64.StdEncoding.DecodeString(v.PublicKey)
		res[i] = DeviceInfo{
			ID: v.ID, PublicKey: ed25519.PublicKey(pk), Role: v.Role,
			PushEndpoint: v.PushEndpoint,
			Capabilities: v.Capabilities, Created: parseTime(v.Created),
			LastSeen: parseTime(v.LastSeen), Revoked: v.Revoked,
		}
	}
	return res, nil
}

// RevokeDevice revokes a device in the account. In a flat account any device may
// revoke any other; in a managed one that is admin-only, and a member revoking
// anything but itself gets 403. Revoking yourself always works.
func (d *Device) RevokeDevice(ctx context.Context, deviceID string) error {
	return d.do(ctx, http.MethodPost, "/v1/devices/"+deviceID+"/revoke", nil, nil)
}

// CreateInvitation mints a single-use token to enroll another device.
func (d *Device) CreateInvitation(ctx context.Context) (Invitation, error) {
	return d.CreateInvitationAs(ctx, "")
}

// CreateInvitationAs mints an invitation granting a specific role. In a managed
// account the role decides what the bearer enrols as, defaulting to RoleMember;
// in a flat account every device enrols as an admin and the server normalises
// the stored grant to match (PRD, decisions 12 and 19). Minting is admin-only.
func (d *Device) CreateInvitationAs(ctx context.Context, role string) (Invitation, error) {
	var in any
	if role != "" {
		in = map[string]string{"grants_role": role}
	}
	var out struct {
		Token   string `json:"invitation_token"`
		ID      string `json:"invitation_id"`
		Expires string `json:"expires"`
	}
	if err := d.do(ctx, http.MethodPost, "/v1/invitations", in, &out); err != nil {
		return Invitation{}, err
	}
	return Invitation{ID: out.ID, Token: out.Token, Expires: parseTime(out.Expires)}, nil
}

// Device roles (PRD, decision 12). A flat account registers every device as
// RoleAdmin; a managed account uses the role its invitation granted.
const (
	RoleAdmin  = "admin"
	RoleMember = "member"
)

// SetRole promotes or demotes a device in the caller's account. Admin-only, and
// refused in a flat account, where every device is an admin as a property of the
// account rather than a coincidence of the current rows. The account's last
// admin cannot be demoted.
func (d *Device) SetRole(ctx context.Context, deviceID, role string) error {
	return d.do(ctx, http.MethodPost, "/v1/devices/"+deviceID+"/role",
		map[string]string{"role": role}, nil)
}

// Quota is a device's own storage accounting. StoredBytes counts the live
// payloads in the queues it owns; QuotaBytes is its ceiling, 0 meaning none.
// AccountQuotaBytes is the shared ceiling, a constant that binds every device
// equally — account *usage* is deliberately not reported, since it would be an
// activity signal about peers (PRD, decision 16).
type Quota struct {
	QuotaBytes        int64
	StoredBytes       int64
	AccountQuotaBytes int64
}

// Quota reads the calling device's own ceiling and usage. Self-scoped by
// construction: it takes no target, so a device cannot ask about a peer. This is
// what lets a capped device tell "I am full" from "someone capped me" — a
// ceiling is set by the operator and is not in the device list.
func (d *Device) Quota(ctx context.Context) (Quota, error) {
	var out struct {
		QuotaBytes        int64 `json:"quota_bytes"`
		StoredBytes       int64 `json:"stored_bytes"`
		AccountQuotaBytes int64 `json:"account_quota_bytes"`
	}
	if err := d.do(ctx, http.MethodGet, "/v1/me/quota", nil, &out); err != nil {
		return Quota{}, err
	}
	return Quota(out), nil
}

// ListInvitations returns the account's outstanding invitations, without tokens.
func (d *Device) ListInvitations(ctx context.Context) ([]Invitation, error) {
	var out struct {
		Invitations []struct {
			ID      string `json:"id"`
			Expires string `json:"expires"`
		} `json:"invitations"`
	}
	if err := d.do(ctx, http.MethodGet, "/v1/invitations", nil, &out); err != nil {
		return nil, err
	}
	res := make([]Invitation, len(out.Invitations))
	for i, v := range out.Invitations {
		res[i] = Invitation{ID: v.ID, Expires: parseTime(v.Expires)}
	}
	return res, nil
}

// RevokeInvitation kills a mis-shared invitation before it is used.
func (d *Device) RevokeInvitation(ctx context.Context, invitationID string) error {
	return d.do(ctx, http.MethodPost, "/v1/invitations/"+invitationID+"/revoke", nil, nil)
}

// SetPushEndpoint registers the device's wake-up endpoint (a UnifiedPush URL);
// an empty string clears it.
func (d *Device) SetPushEndpoint(ctx context.Context, endpoint string) error {
	return d.do(ctx, http.MethodPut, "/v1/me/push", map[string]string{"push_endpoint": endpoint}, nil)
}

// PublishBundle stores the device's opaque key bundle for peers to fetch.
func (d *Device) PublishBundle(ctx context.Context, blob []byte) error {
	return d.do(ctx, http.MethodPut, "/v1/me/bundle", map[string]string{"bundle": b64(blob)}, nil)
}

// GetBundle fetches a peer device's published bundle, verbatim.
func (d *Device) GetBundle(ctx context.Context, deviceID string) ([]byte, error) {
	var out struct {
		Bundle string `json:"bundle"`
	}
	if err := d.do(ctx, http.MethodGet, "/v1/devices/"+deviceID+"/bundle", nil, &out); err != nil {
		return nil, err
	}
	return base64.StdEncoding.DecodeString(out.Bundle)
}

// CreateQueue creates a blind queue owned by this device. recipientKey is the
// public half of a fresh per-queue Ed25519 key the caller generated; the
// matching private key goes into a Recipient.
func (d *Device) CreateQueue(ctx context.Context, recipientKey ed25519.PublicKey) (QueueIDs, error) {
	var out struct {
		RecipientID string `json:"recipient_id"`
		SenderID    string `json:"sender_id"`
	}
	in := map[string]string{"recipient_key": b64(recipientKey)}
	if err := d.do(ctx, http.MethodPost, "/v1/queues", in, &out); err != nil {
		return QueueIDs{}, err
	}
	return QueueIDs{RecipientID: out.RecipientID, SenderID: out.SenderID}, nil
}

// Statement is one entry in an account's administrative log. Blob is opaque to
// Sund and to this package: a consumer signs and encrypts it, and only the
// account's devices can verify or read it.
type Statement struct {
	Seq     int64
	Blob    []byte
	Created time.Time
}

// AppendStatement writes one administrative statement to the account log
// (PRD, decision 21). Admin-only.
//
// The blob must be signed AND encrypted by the caller. Signing is what lets a
// peer tell a real act from one a hostile host invented; encryption is what
// stops the log from becoming the actor-to-target record Sund's data model
// refuses. This package cannot check either — it carries bytes.
func (d *Device) AppendStatement(ctx context.Context, blob []byte) (Statement, error) {
	var out struct {
		Seq       int64  `json:"seq"`
		Statement string `json:"statement"`
		Created   string `json:"created"`
	}
	in := map[string]string{"statement": base64.StdEncoding.EncodeToString(blob)}
	if err := d.do(ctx, http.MethodPost, "/v1/statements", in, &out); err != nil {
		return Statement{}, err
	}
	return Statement{Seq: out.Seq, Blob: blob, Created: parseTime(out.Created)}, nil
}

// Statements reads the account's log from since onward, exclusive. Readable by
// every device in the account, not only admins: the point of the log is that a
// peer can check an act for itself. Pass 0 for everything retained.
//
// A gap in the sequence means entries were trimmed (an account keeps a bounded
// number) or withheld. Signing defeats forgery, not suppression: the host serves
// this log and can truncate it, which no server-stored log can prevent.
func (d *Device) Statements(ctx context.Context, since int64) ([]Statement, error) {
	var out struct {
		Statements []struct {
			Seq       int64  `json:"seq"`
			Statement string `json:"statement"`
			Created   string `json:"created"`
		} `json:"statements"`
	}
	path := "/v1/statements/" + strconv.FormatInt(since, 10)
	if err := d.do(ctx, http.MethodGet, path, nil, &out); err != nil {
		return nil, err
	}
	res := make([]Statement, len(out.Statements))
	for i, v := range out.Statements {
		blob, err := base64.StdEncoding.DecodeString(v.Statement)
		if err != nil {
			return nil, fmt.Errorf("statement %d: %w", v.Seq, err)
		}
		res[i] = Statement{Seq: v.Seq, Blob: blob, Created: parseTime(v.Created)}
	}
	return res, nil
}
