package client

import (
	"context"
	"crypto/ed25519"
	"encoding/base64"
	"net/http"
	"time"

	"github.com/mevoc/sund/internal/sigauth"
)

// Message is one ciphertext envelope drained from a queue. Payload is exactly
// the bytes the sender handed to Send; decrypting it is the caller's job.
type Message struct {
	ID         string
	Payload    []byte
	ReceivedAt time.Time
	Expires    time.Time
}

// Recipient is the owner side of one queue, authenticated by the per-queue
// recipient key whose public half was supplied at CreateQueue.
type Recipient struct {
	conn        *Conn
	RecipientID string
	key         ed25519.PrivateKey
}

// NewRecipient wraps a queue's recipient id and key.
func NewRecipient(conn *Conn, recipientID string, key ed25519.PrivateKey) *Recipient {
	return &Recipient{conn: conn, RecipientID: recipientID, key: key}
}

// Recv drains the queue: every live message, oldest first. Messages stay
// stored until acked, so a crash between Recv and Ack redelivers them.
func (r *Recipient) Recv(ctx context.Context) ([]Message, error) {
	var out struct {
		Messages []struct {
			ID         string `json:"id"`
			Payload    string `json:"payload"`
			ReceivedAt string `json:"received_at"`
			Expires    string `json:"expires"`
		} `json:"messages"`
	}
	if err := r.conn.do(ctx, r.key, http.MethodGet, "/v1/recv/"+r.RecipientID, nil, nil, &out); err != nil {
		return nil, err
	}
	res := make([]Message, len(out.Messages))
	for i, m := range out.Messages {
		payload, err := base64.StdEncoding.DecodeString(m.Payload)
		if err != nil {
			return nil, err
		}
		res[i] = Message{ID: m.ID, Payload: payload, ReceivedAt: parseTime(m.ReceivedAt), Expires: parseTime(m.Expires)}
	}
	return res, nil
}

// Ack deletes the given messages and returns how many were deleted.
func (r *Recipient) Ack(ctx context.Context, ids []string) (int, error) {
	if len(ids) == 0 {
		return 0, nil
	}
	var out struct {
		Deleted int `json:"deleted"`
	}
	in := map[string][]string{"ids": ids}
	if err := r.conn.do(ctx, r.key, http.MethodPost, "/v1/ack/"+r.RecipientID, nil, in, &out); err != nil {
		return 0, err
	}
	return out.Deleted, nil
}

// Retire retires the queue: undelivered messages are dropped and every later
// send to its sender id fails with 404 (fail closed).
func (r *Recipient) Retire(ctx context.Context) error {
	return r.conn.do(ctx, r.key, http.MethodPost, "/v1/retire/"+r.RecipientID, nil, nil, nil)
}

// Sender is the pseudonymous writer side of one queue. It holds the sender id
// and a per-queue Ed25519 key, both handed over out of band by the recipient
// (or generated by the sender and bound on first use — the server binds
// whichever key the first send presents).
type Sender struct {
	conn     *Conn
	SenderID string
	key      ed25519.PrivateKey
}

// NewSender wraps a queue's sender id and per-queue key.
func NewSender(conn *Conn, senderID string, key ed25519.PrivateKey) *Sender {
	return &Sender{conn: conn, SenderID: senderID, key: key}
}

// SendOptions tune one send. A zero TTL means the server default (24 h); the
// server clamps to at most 7 days. Priority is an opaque hint that the wake-up
// ping to the recipient should take the high-priority path (Doze-piercing on
// Android); the payload is unaffected. Note that the host and the push path can
// observe the flag.
type SendOptions struct {
	TTL      time.Duration
	Priority bool
}

// Send appends ciphertext to the queue and returns the server's message id.
// The per-queue public key travels on every send: the server binds it on the
// first send to an open queue and, once bound, merely checks that it matches,
// so the client keeps no "bound yet" state and survives a restart.
func (s *Sender) Send(ctx context.Context, ciphertext []byte, opts SendOptions) (string, error) {
	in := map[string]any{
		"payload":  b64(ciphertext),
		"ttl":      int(opts.TTL / time.Second),
		"priority": opts.Priority,
	}
	h := http.Header{}
	h.Set(sigauth.HeaderSenderKey, b64(s.key.Public().(ed25519.PublicKey)))
	var out struct {
		MessageID string `json:"message_id"`
	}
	if err := s.conn.do(ctx, s.key, http.MethodPost, "/v1/send/"+s.SenderID, h, in, &out); err != nil {
		return "", err
	}
	return out.MessageID, nil
}

// SetQuota sets this queue's storage ceiling in bytes; 0 removes it. It is the
// only quota level a client may write, and the reason is the asymmetry the PRD
// draws (decision 17): capping your own inbound channel limits only what you
// receive, so it is nobody's weapon. The account and device ceilings cap someone
// else and are the operator's alone.
//
// Because a bound queue has exactly one sender, a per-queue ceiling bounds a
// peer — which is how Sund limits a sender without ever recording who it is.
func (r *Recipient) SetQuota(ctx context.Context, quotaBytes int64) error {
	return r.conn.do(ctx, r.key, http.MethodPost, "/v1/quota/"+r.RecipientID,
		nil, map[string]int64{"quota_bytes": quotaBytes}, nil)
}
